Give a clearer status message if no initial re-filtering work is needed

diff --git a/git-rapply b/git-rapply
--- a/git-rapply
+++ b/git-rapply
@@ -121,12 +121,17 @@ filterfiles() {
 # commits are simpler and cleaner
 echo "Performing initial filter operation"
 filterfiles
-git add -A -f .
-git commit -F- <<EOCOMMITMESSAGE || true
+
+if ! git_is_clean; then
+    git add -A -f .
+    git commit -F- <<EOCOMMITMESSAGE || true
 Auto-applying ${COMMAND} to these files first, to make subsequent commits easier to read:
 
 $(git diff --cached  --name-only)
 EOCOMMITMESSAGE
+else
+    echo "Initial state is clean -- no changes required"
+fi
 
 # Utility to reset the working tree contents to a selected sha, while
 # keeping the git repository pointed at the same commit. Done by a
